<template>
  <div class="min-h-screen bg-[#0a0a0f] pt-32 pb-20">
    <div class="container mx-auto px-4 max-w-4xl">
      <h1 class="text-4xl font-bold text-white mb-8">Terms & Conditions</h1>
      <p class="text-gray-500 mb-8">Updated Date: Dec. 3rd, 2025</p>

      <div class="prose prose-invert max-w-none text-gray-400 space-y-6">
        <section>
          <h2 class="text-2xl font-semibold text-white">Welcome to VidGen</h2>
          <p>
            Thank you for visiting VidGen. Through this website, you can access our innovative AI media tools, including our AI video generation and image-to-video services, with more exciting AI media tools planned for the future. By accessing and using our website and services, you agree to be bound by these Terms & Conditions (hereinafter the "Terms").
          </p>
          <p>
            We may modify these Terms & Conditions, as well as the products, features, pricing, and services available on this website, at any time without prior notice. VidGen will actively pursue all legal remedies available to address and rectify any breaches of these Terms & Conditions. Please review these Terms regularly for updates. Your continued use of VidGen following any changes constitutes acceptance of those changes.
          </p>
        </section>

        <section>
          <h2 class="text-2xl font-semibold text-white">Copyright of VidGen</h2>
          <p>
            All content, features, and functionalities available on this website, including but not limited to text, graphics, logos, button icons, images, audio clips, digital downloads, data compilations, software, and AI-generated outputs ("Content") are the exclusive property of VidGen and VIDGEN TECHNOLOGY LIMITED, and are protected by international copyright laws. All rights are expressly reserved.
          </p>
          <p>
            This copyright protection extends to, but is not limited to, the outputs generated by our AI video and image-to-video services, as well as any future AI audio, photo, video and art tools offered on VidGen.
          </p>
          <p>
            Generally, you may not reproduce, distribute, modify, publicly display, publicly perform, republish, download, store, or transmit any of the Content on our website without the prior written consent of VidGen.
          </p>
          <p class="mt-4">There are limited exceptions to this rule for personal, non-commercial use:</p>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong class="text-white">Personal Use Copy:</strong> You may save a copy of pages from this website and its Content to your local computer's hard drive for your personal, non-commercial, informational use only. You are not permitted to further reproduce, distribute, or commercially exploit this saved copy.</li>
            <li><strong class="text-white">Limited Third-Party Sharing:</strong> You may share excerpts of the Content with a third party for their own personal, non-commercial use, provided that you acknowledge VidGen as the source of the Content.</li>
          </ul>
          <p class="mt-4">
            For any commercial use, distribution, or modification of the Content, you must obtain explicit written permission from VidGen. Please contact us through the channels provided on our website for such requests.
          </p>
        </section>

        <section>
          <h2 class="text-2xl font-semibold text-white">Trademarks</h2>
          <p>
            "VidGen", the VidGen logo, and all related names, logos, product and service names, designs, and slogans are trademarks of VidGen and VIDGEN TECHNOLOGY LIMITED or its affiliates or licensors. You must not use such marks without the prior written permission of VidGen.
          </p>
          <p>
            This includes refraining from using the "VidGen" trademark or any confusingly similar marks in connection with any content, software, or other product or service that is not offered or authorized by VidGen. We will vigorously protect our trademarks and enforce our rights under applicable trademark and unfair competition laws.
          </p>
        </section>

        <section>
          <h2 class="text-2xl font-semibold text-white">User Code of Conduct</h2>
          <p>1. When using this service, you shall comply with applicable laws, regulations and policy provisions, and shall not use this service to engage in illegal activities or generate illegal content. It is prohibited to produce, upload, publish, and disseminate the following types of information or behaviors, including but not limited to:</p>
          <ul class="list-disc pl-6 space-y-2">
            <li>(I) Violation of internationally recognized laws and regulations or local laws and regulations of the target market.</li>
            <li>(II) Content that infringes on the rights or interests of others (such as privacy, intellectual property rights, etc.) or the public.</li>
            <li>(III) Spreading hate speech, violence, pornography, terrorism and other content. Content that infringes on the legitimate rights and interests of others or the public interest.</li>
            <li>(IV) Promoting products without VidGen's consent or violating its guidelines.</li>
            <li>(V) Content that undermines the stability of the system or service (such as viruses, malicious code or any program designed to interrupt, destroy or limit the functions of any computer software, etc.)</li>
            <li>(VI) Using the Service to develop or improve products that compete with VidGen.</li>
            <li>(VII) Obtaining content or data generated by the Service through improper means, or conducting reverse engineering, disassembling, or attempting to crack the Service's source code.</li>
            <li>(VIII) Other content prohibited by laws and administrative regulations.</li>
          </ul>
          <p class="mt-4">2. You must ensure that the input content is legal and compliant, and that you have the legal right to use the data or have obtained the necessary authorization. You are solely responsible for any claims arising from uploaded content. You also grant VidGen non-exclusive use rights within the scope of the service.</p>
          <p class="mt-4">3. By using features that involve facial or likeness content (e.g., face swap or portrait-based generation), you represent and warrant that you have obtained all necessary rights, consents, and permissions from any individuals whose likeness is used in the source content (such as image or video). You shall ensure that all source content uploaded for such features complies with applicable laws and does not infringe the intellectual property rights, portrait rights, privacy rights, or other legitimate rights of third parties.</p>
          <p>
            You grant VidGen a limited, non-exclusive license to use the source materials containing facial data solely for the purpose of providing the relevant service. You are solely liable for any infringement or misuse arising from your use of the feature. VidGen reserves the right to refuse to provide such services or remove any content that we reasonably believe violates laws or this Terms (e.g., non-consensual content, fraudulent content) without prior notice.
          </p>
          <p class="mt-4">4. VidGen reserves the right to use automated and human moderation to review the user input content and generated results. If the content violates the regulations or infringes the legitimate right of the third party, VidGen has the right to delete or block the content.</p>
          <p class="mt-4">5. According to the requirements of laws and regulations, VidGen will automatically mark the relevant logo of "generated content belongs to AI generation", and you shall not delete or tamper with such logos without authorization.</p>
        </section>

        <section>
          <h2 class="text-2xl font-semibold text-white">Subscription and Cancellation</h2>
          <p>
            You can subscribe according to the relevant rules. All subscription details including start date, expiration date, and subscription type can be viewed in Member Center within your account. You may cancel your subscription at any time. If you choose to cancel, the current subscription will remain active until the end of the current billing period, after which no further charges will apply. At this point, your access will be limited to the platform's free version, and you will no longer be able to use premium features and content exclusive to paid subscriptions.
          </p>
          <p>
            In order to provide you with a subscription service, we may collect relevant financial information, including bank account, payment information. The relevant data is only used when necessary and is protected by encryption technology.
          </p>
        </section>

        <section>
          <h2 class="text-2xl font-semibold text-white">Links to Other Websites</h2>
          <p>
            Our website may contain links to third-party websites that are not owned or controlled by VidGen. These links are provided for your convenience only and do not imply any endorsement by VidGen of the content, operators, or practices of such third-party websites.
          </p>
          <p>
            VidGen has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third-party websites. By accessing third-party websites through links on VidGen, you acknowledge and agree that your use of such third-party websites is solely at your own risk and discretion. These Terms & Conditions do not apply to your use of third-party websites. We encourage you to review the terms of service and privacy policies of any third-party websites you visit.
          </p>
        </section>

        <section>
          <h2 class="text-2xl font-semibold text-white">Feedback</h2>
          <p>
            We highly value your feedback and are always striving to improve our services and website. We encourage you to share your comments, suggestions, ideas, or any feedback you may have regarding VidGen, our AI video tools, or any of our planned AI media tools. You can contact us through the contact information provided on our website.
          </p>
          <p>
            However, please be aware that by submitting any feedback to VidGen, you grant us a non-exclusive, perpetual, irrevocable, royalty-free, worldwide license to use, reproduce, disclose, distribute, modify, and exploit such feedback for any purpose, without any obligation to compensate you or attribute the feedback to you. We appreciate your contributions, but submission of feedback implies your agreement to these terms.
          </p>
        </section>

        <section>
          <h2 class="text-2xl font-semibold text-white">Indemnity</h2>
          <p>
            By accessing VidGen and using our services, including but not limited to the AI video tools, you agree to indemnify, defend, and hold harmless VidGen, VIDGEN TECHNOLOGY LIMITED, its affiliates, officers, directors, employees, agents, and licensors from and against any and all claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable attorneys' fees) arising out of or relating to:
          </p>
          <ul class="list-disc pl-6 space-y-2">
            <li>(a) Your use of the VidGen website and our services;</li>
            <li>(b) Your violation of these Terms & Conditions;</li>
            <li>(c) Your violation of any applicable laws, rules, or regulations;</li>
            <li>(d) Any content you generate or create using VidGen's services; or</li>
            <li>(e) Your infringement of any intellectual property rights or other rights of any third party.</li>
            <li>You agree not to hold VidGen responsible for any issues, losses, or damages arising from your use of our website, services, or any communication between you and VidGen.</li>
            <li>(f) Your use of features involving facial or likeness content, including any claims related to misuse of biometric data, violation of portrait rights, defamation, or fraud.</li>
          </ul>
        </section>

        <section>
          <h2 class="text-2xl font-semibold text-white">Disclaimer</h2>
          <p>
            VidGen provides its AI media tools, including the AI audio, video, photo and art services, for creative, entertainment, and lawful purposes only. We make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability with respect to the website or the information, products, services, or related graphics contained on the website for any purpose. Any reliance you place on such information is therefore strictly at your own risk.
          </p>
          <div class="mt-4 space-y-4">
            <div>
              <h3 class="text-xl font-semibold text-white mb-2">AI-Generated Content Disclaimer</h3>
              <p>
                You understand and acknowledge that the outputs generated by our AI tools are based on complex algorithms and machine learning models. While we strive to provide high-quality and innovative results, AI-generated content may not always be perfect, unique, or suitable for every purpose. VidGen does not warrant that the AI-generated content will be error-free, meet your specific requirements, or be free from any claims of copyright infringement by third parties (although we take measures to mitigate such risks). You are solely responsible for evaluating the appropriateness and legality of using any AI-generated content for your intended purposes.
              </p>
            </div>
            <div>
              <h3 class="text-xl font-semibold text-white mb-2">Prohibited Uses Disclaimer</h3>
              <p>
                You are strictly prohibited from using the services or AI-generated content for any illegal, infringing, or unethical activities. This includes, but is not limited to, generating or disseminating pornographic, obscene, sexually explicit, violent, hateful, discriminatory, defamatory, or otherwise unlawful material. Users are solely responsible for all content they generate and share through VidGen's tools. And if any third party claims rights to the content you upload or generate, you shall handle it yourself and bear all legal responsibilities. Any violation of this provision may result in the immediate suspension or termination of service access and may expose the user to civil, criminal, or regulatory liability under applicable law. VidGen expressly disclaims all responsibility and liability for any misuse of its services that violates applicable laws or infringes the rights of others. Users shall fully indemnify and hold harmless VidGen and VIDGEN TECHNOLOGY LIMITED for any losses, damages, costs, or expenses (including legal fees) arising from such misuse.
              </p>
            </div>
            <div>
              <h3 class="text-xl font-semibold text-white mb-2">No Legal or Professional Advice</h3>
              <p>
                The information and services provided on VidGen are not intended to constitute legal, financial, medical, or other professional advice. You should consult with a qualified professional for advice tailored to your specific situation.
              </p>
            </div>
          </div>
          <p class="mt-4">
            To the maximum extent permitted by applicable law, in no event shall VidGen or VIDGEN TECHNOLOGY LIMITED be liable for any indirect, consequential, incidental, special, punitive, or exemplary damages, or for any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from:
          </p>
          <ul class="list-disc pl-6 space-y-2 mt-2">
            <li>your use or inability to use VidGen or our services;</li>
            <li>any unauthorized access to or use of our servers and/or any personal information stored therein;</li>
            <li>any interruption or cessation of transmission to or from our services;</li>
            <li>any bugs, viruses, trojan horses, or the like that may be transmitted to or through our services by any third party;</li>
            <li>any errors or omissions in any content; or</li>
            <li>for any loss or damage of any kind incurred as a result of your use of any content posted, emailed, transmitted, or otherwise made available via VidGen, whether based on warranty, contract, tort (including negligence), or any other legal theory, even if VidGen has been advised of the possibility of such damages.</li>
          </ul>
          <p class="mt-4">All rights not expressly granted herein are reserved to and retained by VidGen.</p>
        </section>

        <section>
          <h2 class="text-2xl font-semibold text-white">Complaints and Appeals</h2>
          <p>
            If you believe that your rights have been violated or find illegal information, you can file a complaint to VidGen via email at <a href="mailto:support@vidgenerator.ai" class="text-violet-400 hover:text-violet-300">support@vidgenerator.ai</a>.
          </p>
          <p>
            You can submit relevant materials for appeal, and VidGen will respond within 5 working days after receiving the appeal.
          </p>
        </section>

        <section>
          <h2 class="text-2xl font-semibold text-white">Governing Law</h2>
          <p>
            These Terms of Service and any separate agreements whereby we provide you shall be governed by and construed in accordance with the laws of the United Kingdom, the State of Colorado of the United States of America, and the applicable local laws of the user's jurisdiction in the Asia-Pacific region (including but not limited to Japan, South Korea); in case of any conflict or inconsistency between the foregoing laws, for users residing in or accessing the Services from Colorado, U.S., the laws of Colorado shall prevail; for users in the Asia-Pacific region, the applicable local laws of their jurisdiction shall prevail; for all other users, the laws of the United Kingdom shall prevail.
          </p>
        </section>

        <section>
          <h2 class="text-2xl font-semibold text-white">Company</h2>
          <p>
            VidGen is operated by VIDGEN TECHNOLOGY LIMITED.
          </p>
          <p class="mt-2">
            <strong class="text-white">HK office:</strong> Room 1001, Cloud End, 111 Tung Chau Street, Tai Kok Tsui, Hong Kong
          </p>
        </section>

        <section>
          <h2 class="text-2xl font-semibold text-white">How to Contact Us</h2>
          <p>
            If you have any questions or comments about these Terms & Conditions, please contact us:
          </p>
          <div class="mt-4 space-y-2">
            <p><strong class="text-white">Company Name:</strong> VIDGEN TECHNOLOGY LIMITED</p>
            <p><strong class="text-white">Business Address:</strong> Room 1001, Cloud End, 111 Tung Chau Street, Tai Kok Tsui, Hong Kong</p>
            <p><strong class="text-white">Email:</strong> <a href="mailto:support@vidgenerator.ai" class="text-violet-400 hover:text-violet-300">support@vidgenerator.ai</a></p>
          </div>
        </section>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
useHead({
  title: 'Terms & Conditions - VidGen',
  meta: [
    { name: 'description', content: 'Terms & Conditions for VidGen.' }
  ]
})
</script>
