"""initial_migration

Revision ID: 04dbc2fd92df
Revises: 
Create Date: 2026-08-22 07:52:42.694378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04dbc2fd92df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.create_table('api_library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=True),
    sa.Column('output_type', sa.String(length=50), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_model_id', sa.String(length=200), nullable=False),
    sa.Column('params_schema', sa.JSON(), nullable=False),
    sa.Column('api_docs_url', sa.String(length=500), nullable=True),
    sa.Column('official_price', sa.Float(), nullable=True),
    sa.Column('official_currency', sa.String(length=10), nullable=True),
    sa.Column('official_unit', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_library_api_key'), 'api_library', ['api_key'], unique=True)
    op.create_index(op.f('ix_api_library_id'), 'api_library', ['id'], unique=False)
    op.create_table('blog_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_categories_id'), 'blog_categories', ['id'], unique=False)
    op.create_index(op.f('ix_blog_categories_name'), 'blog_categories', ['name'], unique=True)
    op.create_index(op.f('ix_blog_categories_slug'), 'blog_categories', ['slug'], unique=True)
    op.create_table('blog_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_tags_id'), 'blog_tags', ['id'], unique=False)
    op.create_index(op.f('ix_blog_tags_name'), 'blog_tags', ['name'], unique=True)
    op.create_index(op.f('ix_blog_tags_slug'), 'blog_tags', ['slug'], unique=True)
    op.create_table('category_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('category_name', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('page_path', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('display_description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('show_in_explore', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['category_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_pages_category_name'), 'category_pages', ['category_name'], unique=False)
    op.create_index(op.f('ix_category_pages_id'), 'category_pages', ['id'], unique=False)
    op.create_index(op.f('ix_category_pages_is_active'), 'category_pages', ['is_active'], unique=False)
    op.create_index(op.f('ix_category_pages_level'), 'category_pages', ['level'], unique=False)
    op.create_index(op.f('ix_category_pages_page_path'), 'category_pages', ['page_path'], unique=False)
    op.create_index(op.f('ix_category_pages_parent_id'), 'category_pages', ['parent_id'], unique=False)
    op.create_index(op.f('ix_category_pages_show_in_explore'), 'category_pages', ['show_in_explore'], unique=False)
    op.create_table('effects_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('category_name', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('page_path', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('display_description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('show_in_explore', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['effects_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_effects_pages_category_name'), 'effects_pages', ['category_name'], unique=False)
    op.create_index(op.f('ix_effects_pages_id'), 'effects_pages', ['id'], unique=False)
    op.create_index(op.f('ix_effects_pages_is_active'), 'effects_pages', ['is_active'], unique=False)
    op.create_index(op.f('ix_effects_pages_level'), 'effects_pages', ['level'], unique=False)
    op.create_index(op.f('ix_effects_pages_page_path'), 'effects_pages', ['page_path'], unique=False)
    op.create_index(op.f('ix_effects_pages_parent_id'), 'effects_pages', ['parent_id'], unique=False)
    op.create_index(op.f('ix_effects_pages_show_in_explore'), 'effects_pages', ['show_in_explore'], unique=False)
    op.create_table('generate_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('category_name', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('page_path', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('display_description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['generate_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generate_pages_category_name'), 'generate_pages', ['category_name'], unique=False)
    op.create_index(op.f('ix_generate_pages_id'), 'generate_pages', ['id'], unique=False)
    op.create_index(op.f('ix_generate_pages_is_active'), 'generate_pages', ['is_active'], unique=False)
    op.create_index(op.f('ix_generate_pages_level'), 'generate_pages', ['level'], unique=False)
    op.create_index(op.f('ix_generate_pages_page_path'), 'generate_pages', ['page_path'], unique=False)
    op.create_index(op.f('ix_generate_pages_parent_id'), 'generate_pages', ['parent_id'], unique=False)
    op.create_table('homepage_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False, comment='banner | carousel'),
    sa.Column('config', sa.JSON(), nullable=False, comment='Full configuration JSON'),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homepage_blocks_id'), 'homepage_blocks', ['id'], unique=False)
    op.create_index(op.f('ix_homepage_blocks_type'), 'homepage_blocks', ['type'], unique=False)
    op.create_table('lexicons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('VIOLENCE', 'PORNOGRAPHY', 'ILLEGAL', 'OTHER', name='lexiconcategory'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='lexiconseverity'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lexicons_category'), 'lexicons', ['category'], unique=False)
    op.create_index(op.f('ix_lexicons_enabled'), 'lexicons', ['enabled'], unique=False)
    op.create_index(op.f('ix_lexicons_id'), 'lexicons', ['id'], unique=False)
    op.create_index(op.f('ix_lexicons_severity'), 'lexicons', ['severity'], unique=False)
    op.create_index(op.f('ix_lexicons_word'), 'lexicons', ['word'], unique=True)
    op.create_table('page_seos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_name', sa.String(length=50), nullable=False),
    sa.Column('page_path', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_seos_id'), 'page_seos', ['id'], unique=False)
    op.create_index(op.f('ix_page_seos_page_name'), 'page_seos', ['page_name'], unique=True)
    op.create_table('recharge_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('tag_text', sa.String(length=50), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recharge_packages_id'), 'recharge_packages', ['id'], unique=False)
    op.create_index(op.f('ix_recharge_packages_is_active'), 'recharge_packages', ['is_active'], unique=False)
    op.create_table('seo_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seo_configs_config_key'), 'seo_configs', ['config_key'], unique=True)
    op.create_index(op.f('ix_seo_configs_id'), 'seo_configs', ['id'], unique=False)
    op.create_table('system_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_group', sa.String(length=50), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_config_group'), 'system_configs', ['config_group'], unique=False)
    op.create_index(op.f('ix_system_configs_config_key'), 'system_configs', ['config_key'], unique=True)
    op.create_index(op.f('ix_system_configs_id'), 'system_configs', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handle', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('instagram_handle', sa.String(length=100), nullable=True),
    sa.Column('twitter_handle', sa.String(length=100), nullable=True),
    sa.Column('discord_handle', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY', name='gender'), nullable=True),
    sa.Column('source', sa.Enum('REGISTER', 'GOOGLE', 'ADMIN_CREATED', 'IMPORT', name='usersource'), server_default='REGISTER', nullable=False),
    sa.Column('handle_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_credits', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_handle'), 'users', ['handle'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta_title', sa.String(length=200), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('meta_keywords', sa.String(length=500), nullable=True),
    sa.Column('og_image', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='poststatus'), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['blog_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_posts_author_id'), 'blog_posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_blog_posts_category'), 'blog_posts', ['category'], unique=False)
    op.create_index(op.f('ix_blog_posts_created_at'), 'blog_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_blog_posts_id'), 'blog_posts', ['id'], unique=False)
    op.create_index(op.f('ix_blog_posts_is_featured'), 'blog_posts', ['is_featured'], unique=False)
    op.create_index(op.f('ix_blog_posts_published_at'), 'blog_posts', ['published_at'], unique=False)
    op.create_index(op.f('ix_blog_posts_slug'), 'blog_posts', ['slug'], unique=True)
    op.create_index(op.f('ix_blog_posts_status'), 'blog_posts', ['status'], unique=False)
    op.create_index(op.f('ix_blog_posts_title'), 'blog_posts', ['title'], unique=False)
    op.create_table('checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('check_date', sa.Date(), nullable=False),
    sa.Column('consecutive_days', sa.Integer(), nullable=False),
    sa.Column('reward_credits', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'check_date', name='uq_user_check_date')
    )
    op.create_index(op.f('ix_checkins_check_date'), 'checkins', ['check_date'], unique=False)
    op.create_index(op.f('ix_checkins_id'), 'checkins', ['id'], unique=False)
    op.create_index(op.f('ix_checkins_user_id'), 'checkins', ['user_id'], unique=False)
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id', name='_follower_following_uc')
    )
    op.create_index(op.f('ix_follows_id'), 'follows', ['id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.Integer(), nullable=True),
    sa.Column('invite_code', sa.String(length=20), nullable=False),
    sa.Column('reward_granted', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_id'), 'invitations', ['id'], unique=False)
    op.create_index(op.f('ix_invitations_invite_code'), 'invitations', ['invite_code'], unique=True)
    op.create_index(op.f('ix_invitations_invitee_id'), 'invitations', ['invitee_id'], unique=False)
    op.create_index(op.f('ix_invitations_inviter_id'), 'invitations', ['inviter_id'], unique=False)
    op.create_index(op.f('ix_invitations_status'), 'invitations', ['status'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', 'AUDIO', 'DOCUMENT', name='mediatype'), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('storage_type', sa.String(length=20), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_created_at'), 'media', ['created_at'], unique=False)
    op.create_index(op.f('ix_media_id'), 'media', ['id'], unique=False)
    op.create_index(op.f('ix_media_media_type'), 'media', ['media_type'], unique=False)
    op.create_index(op.f('ix_media_source'), 'media', ['source'], unique=False)
    op.create_index(op.f('ix_media_user_id'), 'media', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('SYSTEM', 'TASK_COMPLETE', 'TASK_FAILED', 'NEW_LIKE', 'NEW_COMMENT', 'NEW_FOLLOW', 'FEATURED', 'CREDIT_UPDATE', 'ACCOUNT_STATUS_CHANGED', 'NSFW_APPROVED', 'NSFW_BLOCKED', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('payment_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('extra_credits_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('paypal_order_id', sa.String(length=255), nullable=True),
    sa.Column('paypal_payment_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_session_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('payment_provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', name='paymentstatus'), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_orders_created_at'), 'payment_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_orders_id'), 'payment_orders', ['id'], unique=False)
    op.create_index(op.f('ix_payment_orders_paypal_order_id'), 'payment_orders', ['paypal_order_id'], unique=True)
    op.create_index(op.f('ix_payment_orders_status'), 'payment_orders', ['status'], unique=False)
    op.create_index(op.f('ix_payment_orders_stripe_payment_intent_id'), 'payment_orders', ['stripe_payment_intent_id'], unique=True)
    op.create_index(op.f('ix_payment_orders_stripe_session_id'), 'payment_orders', ['stripe_session_id'], unique=True)
    op.create_index(op.f('ix_payment_orders_user_id'), 'payment_orders', ['user_id'], unique=False)
    op.create_table('recharge_promos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('extra_credits_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('promo_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recharge_promos_id'), 'recharge_promos', ['id'], unique=False)
    op.create_index(op.f('ix_recharge_promos_promo_code'), 'recharge_promos', ['promo_code'], unique=True)
    op.create_index(op.f('ix_recharge_promos_user_id'), 'recharge_promos', ['user_id'], unique=False)
    op.create_table('user_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'activity_date', name='uq_user_activity_date')
    )
    op.create_index(op.f('ix_user_activity_logs_activity_date'), 'user_activity_logs', ['activity_date'], unique=False)
    op.create_index(op.f('ix_user_activity_logs_id'), 'user_activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_user_activity_logs_user_id'), 'user_activity_logs', ['user_id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('work_type', sa.String(length=50), nullable=False),
    sa.Column('nodes', sa.JSON(), nullable=False),
    sa.Column('edges', sa.JSON(), nullable=False),
    sa.Column('viewport', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.create_index(op.f('ix_workflows_is_active'), 'workflows', ['is_active'], unique=False)
    op.create_index(op.f('ix_workflows_work_type'), 'workflows', ['work_type'], unique=False)
    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('prompt_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('model_key', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('storage_key', sa.String(length=50), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('short_code', sa.String(length=11), nullable=True),
    sa.Column('url_slug', sa.String(length=250), nullable=True),
    sa.Column('status', sa.Enum('GENERATING', 'PROCESSING', 'SUCCESS', 'FAILED', name='workstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('replicate_id', sa.String(length=255), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('share_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='sharestatus'), nullable=True),
    sa.Column('share_name', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('ban_reason', sa.Text(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('nsfw_status', sa.String(length=20), nullable=True),
    sa.Column('nsfw_tags', sa.JSON(), nullable=True),
    sa.Column('auto_moderated', sa.Boolean(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('favorite_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['works.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_works_auto_moderated'), 'works', ['auto_moderated'], unique=False)
    op.create_index(op.f('ix_works_category'), 'works', ['category'], unique=False)
    op.create_index(op.f('ix_works_created_at'), 'works', ['created_at'], unique=False)
    op.create_index(op.f('ix_works_deleted_at'), 'works', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_works_hidden'), 'works', ['hidden'], unique=False)
    op.create_index(op.f('ix_works_id'), 'works', ['id'], unique=False)
    op.create_index(op.f('ix_works_is_banned'), 'works', ['is_banned'], unique=False)
    op.create_index(op.f('ix_works_is_featured'), 'works', ['is_featured'], unique=False)
    op.create_index(op.f('ix_works_is_shared'), 'works', ['is_shared'], unique=False)
    op.create_index(op.f('ix_works_model_key'), 'works', ['model_key'], unique=False)
    op.create_index(op.f('ix_works_model_name'), 'works', ['model_name'], unique=False)
    op.create_index(op.f('ix_works_nsfw_status'), 'works', ['nsfw_status'], unique=False)
    op.create_index(op.f('ix_works_parent_id'), 'works', ['parent_id'], unique=False)
    op.create_index(op.f('ix_works_prompt_id'), 'works', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_works_replicate_id'), 'works', ['replicate_id'], unique=True)
    op.create_index(op.f('ix_works_share_status'), 'works', ['share_status'], unique=False)
    op.create_index(op.f('ix_works_short_code'), 'works', ['short_code'], unique=True)
    op.create_index(op.f('ix_works_status'), 'works', ['status'], unique=False)
    op.create_index(op.f('ix_works_storage_key'), 'works', ['storage_key'], unique=False)
    op.create_index(op.f('ix_works_type'), 'works', ['type'], unique=False)
    op.create_index(op.f('ix_works_url_slug'), 'works', ['url_slug'], unique=True)
    op.create_index(op.f('ix_works_user_id'), 'works', ['user_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_created_at'), 'comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_comments_parent_id'), 'comments', ['parent_id'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_index(op.f('ix_comments_work_id'), 'comments', ['work_id'], unique=False)
    op.create_table('credit_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('RECHARGE', 'GIFT', 'CONSUME', 'REFUND', name='credittype'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['payment_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_records_created_at'), 'credit_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_credit_records_expire_at'), 'credit_records', ['expire_at'], unique=False)
    op.create_index(op.f('ix_credit_records_id'), 'credit_records', ['id'], unique=False)
    op.create_index(op.f('ix_credit_records_type'), 'credit_records', ['type'], unique=False)
    op.create_index(op.f('ix_credit_records_user_id'), 'credit_records', ['user_id'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'work_id', name='unique_user_work_favorite')
    )
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_index(op.f('ix_favorites_work_id'), 'favorites', ['work_id'], unique=False)
    op.create_table('generation_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('model_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('work_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('model_level', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('params_config', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('example_galleries', sa.JSON(), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('badge', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_models_id'), 'generation_models', ['id'], unique=False)
    op.create_index(op.f('ix_generation_models_is_active'), 'generation_models', ['is_active'], unique=False)
    op.create_index(op.f('ix_generation_models_is_featured'), 'generation_models', ['is_featured'], unique=False)
    op.create_index(op.f('ix_generation_models_model_key'), 'generation_models', ['model_key'], unique=True)
    op.create_index(op.f('ix_generation_models_work_type'), 'generation_models', ['work_type'], unique=False)
    op.create_index(op.f('ix_generation_models_workflow_id'), 'generation_models', ['workflow_id'], unique=False)
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'work_id', name='uix_user_work_like')
    )
    op.create_index(op.f('ix_likes_id'), 'likes', ['id'], unique=False)
    op.create_index(op.f('ix_likes_user_id'), 'likes', ['user_id'], unique=False)
    op.create_index(op.f('ix_likes_work_id'), 'likes', ['work_id'], unique=False)
    op.create_table('moderation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('moderation_type', sa.Enum('NSFW', 'SHARE_REVIEW', name='moderationtype'), nullable=False),
    sa.Column('action_type', sa.Enum('AUTO_BLOCKED', 'AUTO_FLAGGED', 'MANUAL_FLAGGED', 'AUTO_APPROVED', 'MANUAL_APPROVED', 'MANUAL_REJECTED', name='moderationaction'), nullable=False),
    sa.Column('nsfw_tags', sa.JSON(), nullable=True),
    sa.Column('flagged_keywords', sa.JSON(), nullable=True),
    sa.Column('moderator_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['moderator_id'], ['admins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_logs_action_type'), 'moderation_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_moderation_logs_created_at'), 'moderation_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_moderation_logs_id'), 'moderation_logs', ['id'], unique=False)
    op.create_index(op.f('ix_moderation_logs_moderation_type'), 'moderation_logs', ['moderation_type'], unique=False)
    op.create_index(op.f('ix_moderation_logs_moderator_id'), 'moderation_logs', ['moderator_id'], unique=False)
    op.create_index(op.f('ix_moderation_logs_work_id'), 'moderation_logs', ['work_id'], unique=False)
    op.create_index('ix_moderation_logs_work_type', 'moderation_logs', ['work_id', 'moderation_type'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.Enum('PORNOGRAPHY', 'VIOLENCE', 'GORE', 'HARASSMENT', 'SPAM', 'COPYRIGHT', 'OTHER', name='reporttype'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RESOLVED', 'DISMISSED', name='reportstatus'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolution_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['admins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_report_type'), 'reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_reports_reporter_id'), 'reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_reports_resolved_by'), 'reports', ['resolved_by'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_index('ix_reports_status_created', 'reports', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_reports_work_id'), 'reports', ['work_id'], unique=False)
    op.create_index('ix_reports_work_status', 'reports', ['work_id', 'status'], unique=False)
    op.create_table('model_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('generation_model_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('meta_title', sa.String(length=200), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('meta_keywords', sa.String(length=500), nullable=True),
    sa.Column('og_image', sa.Text(), nullable=True),
    sa.Column('featured_image', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='modelpagestatus'), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['generation_model_id'], ['generation_models.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_pages_created_at'), 'model_pages', ['created_at'], unique=False)
    op.create_index(op.f('ix_model_pages_generation_model_id'), 'model_pages', ['generation_model_id'], unique=True)
    op.create_index(op.f('ix_model_pages_id'), 'model_pages', ['id'], unique=False)
    op.create_index(op.f('ix_model_pages_published_at'), 'model_pages', ['published_at'], unique=False)
    op.create_index(op.f('ix_model_pages_slug'), 'model_pages', ['slug'], unique=True)
    op.create_index(op.f('ix_model_pages_status'), 'model_pages', ['status'], unique=False)
    op.create_index(op.f('ix_model_pages_title'), 'model_pages', ['title'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('meta_title', sa.String(length=200), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('meta_keywords', sa.String(length=500), nullable=True),
    sa.Column('og_image', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('featured_image', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('generation_model_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='topicstatus'), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['blog_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['generation_model_id'], ['generation_models.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_category'), 'topics', ['category'], unique=False)
    op.create_index(op.f('ix_topics_created_at'), 'topics', ['created_at'], unique=False)
    op.create_index(op.f('ix_topics_generation_model_id'), 'topics', ['generation_model_id'], unique=True)
    op.create_index(op.f('ix_topics_id'), 'topics', ['id'], unique=False)
    op.create_index(op.f('ix_topics_is_featured'), 'topics', ['is_featured'], unique=False)
    op.create_index(op.f('ix_topics_published_at'), 'topics', ['published_at'], unique=False)
    op.create_index(op.f('ix_topics_slug'), 'topics', ['slug'], unique=True)
    op.create_index(op.f('ix_topics_status'), 'topics', ['status'], unique=False)
    op.create_index(op.f('ix_topics_title'), 'topics', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topics_title'), table_name='topics')
    op.drop_index(op.f('ix_topics_status'), table_name='topics')
    op.drop_index(op.f('ix_topics_slug'), table_name='topics')
    op.drop_index(op.f('ix_topics_published_at'), table_name='topics')
    op.drop_index(op.f('ix_topics_is_featured'), table_name='topics')
    op.drop_index(op.f('ix_topics_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_generation_model_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_created_at'), table_name='topics')
    op.drop_index(op.f('ix_topics_category'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_model_pages_title'), table_name='model_pages')
    op.drop_index(op.f('ix_model_pages_status'), table_name='model_pages')
    op.drop_index(op.f('ix_model_pages_slug'), table_name='model_pages')
    op.drop_index(op.f('ix_model_pages_published_at'), table_name='model_pages')
    op.drop_index(op.f('ix_model_pages_id'), table_name='model_pages')
    op.drop_index(op.f('ix_model_pages_generation_model_id'), table_name='model_pages')
    op.drop_index(op.f('ix_model_pages_created_at'), table_name='model_pages')
    op.drop_table('model_pages')
    op.drop_index('ix_reports_work_status', table_name='reports')
    op.drop_index(op.f('ix_reports_work_id'), table_name='reports')
    op.drop_index('ix_reports_status_created', table_name='reports')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_resolved_by'), table_name='reports')
    op.drop_index(op.f('ix_reports_reporter_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_moderation_logs_work_type', table_name='moderation_logs')
    op.drop_index(op.f('ix_moderation_logs_work_id'), table_name='moderation_logs')
    op.drop_index(op.f('ix_moderation_logs_moderator_id'), table_name='moderation_logs')
    op.drop_index(op.f('ix_moderation_logs_moderation_type'), table_name='moderation_logs')
    op.drop_index(op.f('ix_moderation_logs_id'), table_name='moderation_logs')
    op.drop_index(op.f('ix_moderation_logs_created_at'), table_name='moderation_logs')
    op.drop_index(op.f('ix_moderation_logs_action_type'), table_name='moderation_logs')
    op.drop_table('moderation_logs')
    op.drop_index(op.f('ix_likes_work_id'), table_name='likes')
    op.drop_index(op.f('ix_likes_user_id'), table_name='likes')
    op.drop_index(op.f('ix_likes_id'), table_name='likes')
    op.drop_table('likes')
    op.drop_index(op.f('ix_generation_models_workflow_id'), table_name='generation_models')
    op.drop_index(op.f('ix_generation_models_work_type'), table_name='generation_models')
    op.drop_index(op.f('ix_generation_models_model_key'), table_name='generation_models')
    op.drop_index(op.f('ix_generation_models_is_featured'), table_name='generation_models')
    op.drop_index(op.f('ix_generation_models_is_active'), table_name='generation_models')
    op.drop_index(op.f('ix_generation_models_id'), table_name='generation_models')
    op.drop_table('generation_models')
    op.drop_index(op.f('ix_favorites_work_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_credit_records_user_id'), table_name='credit_records')
    op.drop_index(op.f('ix_credit_records_type'), table_name='credit_records')
    op.drop_index(op.f('ix_credit_records_id'), table_name='credit_records')
    op.drop_index(op.f('ix_credit_records_expire_at'), table_name='credit_records')
    op.drop_index(op.f('ix_credit_records_created_at'), table_name='credit_records')
    op.drop_table('credit_records')
    op.drop_index(op.f('ix_comments_work_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_parent_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_created_at'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_works_user_id'), table_name='works')
    op.drop_index(op.f('ix_works_url_slug'), table_name='works')
    op.drop_index(op.f('ix_works_type'), table_name='works')
    op.drop_index(op.f('ix_works_storage_key'), table_name='works')
    op.drop_index(op.f('ix_works_status'), table_name='works')
    op.drop_index(op.f('ix_works_short_code'), table_name='works')
    op.drop_index(op.f('ix_works_share_status'), table_name='works')
    op.drop_index(op.f('ix_works_replicate_id'), table_name='works')
    op.drop_index(op.f('ix_works_prompt_id'), table_name='works')
    op.drop_index(op.f('ix_works_parent_id'), table_name='works')
    op.drop_index(op.f('ix_works_nsfw_status'), table_name='works')
    op.drop_index(op.f('ix_works_model_name'), table_name='works')
    op.drop_index(op.f('ix_works_model_key'), table_name='works')
    op.drop_index(op.f('ix_works_is_shared'), table_name='works')
    op.drop_index(op.f('ix_works_is_featured'), table_name='works')
    op.drop_index(op.f('ix_works_is_banned'), table_name='works')
    op.drop_index(op.f('ix_works_id'), table_name='works')
    op.drop_index(op.f('ix_works_hidden'), table_name='works')
    op.drop_index(op.f('ix_works_deleted_at'), table_name='works')
    op.drop_index(op.f('ix_works_created_at'), table_name='works')
    op.drop_index(op.f('ix_works_category'), table_name='works')
    op.drop_index(op.f('ix_works_auto_moderated'), table_name='works')
    op.drop_table('works')
    op.drop_index(op.f('ix_workflows_work_type'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_is_active'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_user_activity_logs_user_id'), table_name='user_activity_logs')
    op.drop_index(op.f('ix_user_activity_logs_id'), table_name='user_activity_logs')
    op.drop_index(op.f('ix_user_activity_logs_activity_date'), table_name='user_activity_logs')
    op.drop_table('user_activity_logs')
    op.drop_index(op.f('ix_recharge_promos_user_id'), table_name='recharge_promos')
    op.drop_index(op.f('ix_recharge_promos_promo_code'), table_name='recharge_promos')
    op.drop_index(op.f('ix_recharge_promos_id'), table_name='recharge_promos')
    op.drop_table('recharge_promos')
    op.drop_index(op.f('ix_payment_orders_user_id'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_stripe_session_id'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_stripe_payment_intent_id'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_status'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_paypal_order_id'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_id'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_created_at'), table_name='payment_orders')
    op.drop_table('payment_orders')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_media_user_id'), table_name='media')
    op.drop_index(op.f('ix_media_source'), table_name='media')
    op.drop_index(op.f('ix_media_media_type'), table_name='media')
    op.drop_index(op.f('ix_media_id'), table_name='media')
    op.drop_index(op.f('ix_media_created_at'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_invitations_status'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_inviter_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_invitee_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_invite_code'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_id'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_follows_id'), table_name='follows')
    op.drop_table('follows')
    op.drop_index(op.f('ix_checkins_user_id'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_id'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_check_date'), table_name='checkins')
    op.drop_table('checkins')
    op.drop_index(op.f('ix_blog_posts_title'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_status'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_slug'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_published_at'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_is_featured'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_id'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_created_at'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_category'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_author_id'), table_name='blog_posts')
    op.drop_table('blog_posts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_handle'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_configs_id'), table_name='system_configs')
    op.drop_index(op.f('ix_system_configs_config_key'), table_name='system_configs')
    op.drop_index(op.f('ix_system_configs_config_group'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_seo_configs_id'), table_name='seo_configs')
    op.drop_index(op.f('ix_seo_configs_config_key'), table_name='seo_configs')
    op.drop_table('seo_configs')
    op.drop_index(op.f('ix_recharge_packages_is_active'), table_name='recharge_packages')
    op.drop_index(op.f('ix_recharge_packages_id'), table_name='recharge_packages')
    op.drop_table('recharge_packages')
    op.drop_index(op.f('ix_page_seos_page_name'), table_name='page_seos')
    op.drop_index(op.f('ix_page_seos_id'), table_name='page_seos')
    op.drop_table('page_seos')
    op.drop_index(op.f('ix_lexicons_word'), table_name='lexicons')
    op.drop_index(op.f('ix_lexicons_severity'), table_name='lexicons')
    op.drop_index(op.f('ix_lexicons_id'), table_name='lexicons')
    op.drop_index(op.f('ix_lexicons_enabled'), table_name='lexicons')
    op.drop_index(op.f('ix_lexicons_category'), table_name='lexicons')
    op.drop_table('lexicons')
    op.drop_index(op.f('ix_homepage_blocks_type'), table_name='homepage_blocks')
    op.drop_index(op.f('ix_homepage_blocks_id'), table_name='homepage_blocks')
    op.drop_table('homepage_blocks')
    op.drop_index(op.f('ix_generate_pages_parent_id'), table_name='generate_pages')
    op.drop_index(op.f('ix_generate_pages_page_path'), table_name='generate_pages')
    op.drop_index(op.f('ix_generate_pages_level'), table_name='generate_pages')
    op.drop_index(op.f('ix_generate_pages_is_active'), table_name='generate_pages')
    op.drop_index(op.f('ix_generate_pages_id'), table_name='generate_pages')
    op.drop_index(op.f('ix_generate_pages_category_name'), table_name='generate_pages')
    op.drop_table('generate_pages')
    op.drop_index(op.f('ix_effects_pages_show_in_explore'), table_name='effects_pages')
    op.drop_index(op.f('ix_effects_pages_parent_id'), table_name='effects_pages')
    op.drop_index(op.f('ix_effects_pages_page_path'), table_name='effects_pages')
    op.drop_index(op.f('ix_effects_pages_level'), table_name='effects_pages')
    op.drop_index(op.f('ix_effects_pages_is_active'), table_name='effects_pages')
    op.drop_index(op.f('ix_effects_pages_id'), table_name='effects_pages')
    op.drop_index(op.f('ix_effects_pages_category_name'), table_name='effects_pages')
    op.drop_table('effects_pages')
    op.drop_index(op.f('ix_category_pages_show_in_explore'), table_name='category_pages')
    op.drop_index(op.f('ix_category_pages_parent_id'), table_name='category_pages')
    op.drop_index(op.f('ix_category_pages_page_path'), table_name='category_pages')
    op.drop_index(op.f('ix_category_pages_level'), table_name='category_pages')
    op.drop_index(op.f('ix_category_pages_is_active'), table_name='category_pages')
    op.drop_index(op.f('ix_category_pages_id'), table_name='category_pages')
    op.drop_index(op.f('ix_category_pages_category_name'), table_name='category_pages')
    op.drop_table('category_pages')
    op.drop_index(op.f('ix_blog_tags_slug'), table_name='blog_tags')
    op.drop_index(op.f('ix_blog_tags_name'), table_name='blog_tags')
    op.drop_index(op.f('ix_blog_tags_id'), table_name='blog_tags')
    op.drop_table('blog_tags')
    op.drop_index(op.f('ix_blog_categories_slug'), table_name='blog_categories')
    op.drop_index(op.f('ix_blog_categories_name'), table_name='blog_categories')
    op.drop_index(op.f('ix_blog_categories_id'), table_name='blog_categories')
    op.drop_table('blog_categories')
    op.drop_index(op.f('ix_api_library_id'), table_name='api_library')
    op.drop_index(op.f('ix_api_library_api_key'), table_name='api_library')
    op.drop_table('api_library')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
